# Form implementation generated from reading ui file 'app.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1080, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        MainWindow.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.loginButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.loginButton.setGeometry(QtCore.QRect(10, 10, 181, 51))
        self.loginButton.setObjectName("loginButton")
        self.songDetailsLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.songDetailsLabel.setGeometry(QtCore.QRect(320, 30, 641, 111))
        self.songDetailsLabel.setObjectName("songDetailsLabel")
        self.bgColorButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.bgColorButton.setGeometry(QtCore.QRect(10, 60, 181, 51))
        self.bgColorButton.setObjectName("bgColorButton")
        self.albumArtLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.albumArtLabel.setGeometry(QtCore.QRect(30, 450, 240, 240))
        self.albumArtLabel.setObjectName("albumArtLabel")
        self.updateButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.updateButton_2.setGeometry(QtCore.QRect(10, 110, 181, 51))
        self.updateButton_2.setObjectName("updateButton_2")
        self.checkBox = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(200, 30, 111, 20))
        self.checkBox.setObjectName("checkBox")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Spotistyle"))
        self.loginButton.setText(_translate("MainWindow", "Login"))
        self.songDetailsLabel.setText(_translate("MainWindow", "current song"))
        self.bgColorButton.setText(_translate("MainWindow", "change bg color"))
        self.albumArtLabel.setText(_translate("MainWindow", "album art"))
        self.updateButton_2.setText(_translate("MainWindow", "update track"))
        self.checkBox.setText(_translate("MainWindow", "remember me"))
